spring.application.name=eva-springbatch
spring.datasource.url=jdbc:postgresql://localhost:5555/evadb
server.port=9090
spring.datasource.username=evauser
spring.datasource.password=Test123
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false
